zalandoresearch/fashion-mnist

README.md
made them all singular with this PR
=> consistent label descriptions

README.md
add benchmark mentioned in #8 and #10, however, source code is missing in #10
=> 8-add-benchmark

README.md
update wideresnet and dense net and freezeout links in the benchmark
=> 10-fix links of WRN and DN

README.md
=> added R darch package

README.zh-CN.md
=> added darch to CN readme

README.md, README.zh-CN.md
=> add new benchmark for resnet

README-ja.md, README.zh-CN.md
=> add japanese README

.catwatch.yaml, .zappr.yaml
=> add zappr and catwatch

README-ja.md, README.md, README.zh-CN.md
this fixes #33, fixes #34, fixes #35
=> add more benchmarks

README.ja.md, README.md, README.zh-CN.md
#36 #41 made the same mistake when using Tensorflow. I added some notice to let people know about this.
=> add some notice on tensorflow loading

README.ja.md, README.md, README.zh-CN.md
add other ml libraries support, fix #28
=> add other ml libraries support

README.ja.md, README.md, README.zh-CN.md
Kashif made a PR to pytorch https://github.com/pytorch/vision/pull/238, and it has been merged.
=> add pytorch support

README.ja.md, README.md, README.zh-CN.md
=> Add more edward and tf master

README.ja.md, README.md, README.zh-CN.md
=> add more benchmark

README.ja.md, README.md, README.zh-CN.md
=> add juliaml supports

README.ja.md, README.md, README.zh-CN.md
=> fix some links

README.ja.md, README.md, README.zh-CN.md
=> add hog svm benchmark

README.ja.md, README.md, README.zh-CN.md
- fix #76 
- add chainer and brine.io helper
=> Add chainer

README.ja.md, README.md, README.zh-CN.md
=> add denser to benchmark

README.ja.md, README.md, README.zh-CN.md
Update MLP value of Fashion Mnist Dataset. In the repository the author provides the code in Keras with test accuracy and the train/loss curves and logs.
=> Update MLP value of Fashion-Mnist

README.ja.md, README.md, README.zh-CN.md
- fix google scholar link
- add link to tf tutorial page
=> Fix link and text

README.ja.md, README.md, README.zh-CN.md
=> add benchmark

README.ja.md, README.md, README.zh-CN.md
=> add benchmark 124

README.md
New link points to specific Gluon API to load Fashion MNIST
=> Updated MXNet Gluon link
